// CommandResult.cs — Domain model representing the result of a remote shell command.
// This is NOT mapped from a database table. It's constructed in-memory by
// SignalRCommandDispatcher after the device responds via the SignalR hub.

namespace ControlIT.Api.Domain.Models;

/// <summary>
/// The result returned after dispatching a remote shell command to a managed device.
/// Constructed from the SignalR response — not a database-mapped class.
/// </summary>
public class CommandResult
{
    // Internal correlation ID — generated by ControlIT for tracking (not used by NetLock protocol)
    public string ResponseId { get; set; } = string.Empty;

    // The device's access_key or device_id — identifies which device produced this output
    public string DeviceId { get; set; } = string.Empty;

    // The raw shell output from the device (stdout/stderr combined)
    public string Output { get; set; } = string.Empty;

    // When the command completed on the ControlIT side (not necessarily device-side)
    public DateTime ExecutedAt { get; set; }

    // "SUCCESS" | "TIMEOUT" | "FAILURE"
    // SUCCESS: device responded with output within the timeout window
    // TIMEOUT: no response received before the TimeoutSeconds limit
    // FAILURE: SignalR error or device error during dispatch
    public string Status { get; set; } = string.Empty;
}
